version: "2"
services:
  webserver:
    image: "moodlehq/moodle-php-apache:${MOODLE_DOCKER_PHP_VERSION}"
    container_name: "webserver"
    build:
      context: "."
      dockerfile: "./dockerfiles/Dockerfilewebserver"
      args:
        MOODLE_DOCKER_PHP_VERSION: "${MOODLE_DOCKER_PHP_VERSION}"
    volumes:
      - "${MOODLE_DOCKER_WWWROOT}:/var/www/html"
      - "${ASSETDIR}/web/apache/apache2_faildumps.conf:/etc/apache2/conf-enabled/apache2_faildumps.conf"
      - "${ASSETDIR}/web/apache/apache2_directory.conf:/etc/apache2/conf-enabled/apache2_directory.conf"
    environment:
      MOODLE_DOCKER_DBNAME: moodle
      MOODLE_DOCKER_DBUSER: moodle
      MOODLE_DOCKER_DBPASS: "m@0dl3ing"
      MOODLE_DOCKER_BROWSER: "${MOODLE_DOCKER_BROWSER}"
      MOODLE_DOCKER_WEB_HOST: "${MOODLE_DOCKER_WEB_HOST}"
      MOODLE_DOCKER_WEB_PORT: "${MOODLE_DOCKER_WEB_PORT}"
  exttests:
    image: "moodlehq/moodle-exttests"
    container_name: "exttests"
    volumes:
      - "${ASSETDIR}/exttests/apache2_ports.conf:/etc/apache2/ports.conf"
      - "${ASSETDIR}/exttests/apache2.conf:/etc/apache2/sites-enabled/000-default.conf"
  selenium:
    image: "selenium/standalone-firefox${MOODLE_DOCKER_SELENIUM_SUFFIX}:${MOODLE_DOCKER_BROWSER_TAG}"
    container_name: "selenium"
    volumes:
      - "${MOODLE_DOCKER_WWWROOT}:/var/www/html:ro"
