version: "2"
services:
  selenium:
    image: "seleniarm/standalone-chromium:latest"
    shm_size: '3gb'
    ports:
      - "4444:4444"
      - "5900:5900"
      - "7900:7900"
    volumes:
      - /dev/shm:/dev/shm
