version: "2"
services:
  webserver:
    volumes:
      - "${ASSETDIR}/web/apache/apache2_mailhog.conf:/etc/apache2/conf-enabled/apache2_mailhog.conf"
    depends_on:
      - mailhog
  mailhog:
    image: "mailhog/mailhog"
    container_name: "mailhog-beta"
    ports:
      - "8025:8025"
