[xdebug]
zend_extension=xdebug
xdebug.mode=debug
xdebug.client_host=host.docker.internal
#xdebug.idekey="PHPSTORM"
xdebug.idekey="vsc"
xdebug.discover_client_host=1
xdebug.start_with_request=1
# PROFILING
#xdebug.mode = profile
#xdebug.start_with_request = trigger
#xdebug.trigger_value = ProfileMe
#xdebug.output_dir = /var/www/html/profiling